CONTINUOS DELIVERY- added instance refresh

diff --git a/.github/workflows/build-ami-on-merge.yml b/.github/workflows/build-ami-on-merge.yml
--- a/.github/workflows/build-ami-on-merge.yml
+++ b/.github/workflows/build-ami-on-merge.yml
@@ -42,88 +42,41 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: packer build main.pkr.hcl
 
-# name: Build AMI after PR Merge
+      - name: Instance Refresh automation / Continuous Delivery
+        run: |
+          sudo apt-get install jq
+          ASG_NAME=${{secrets.ASGNAME }}  
+          LAUNCH_CONFIG=${{secrets.LaunchTemplateName }}
+          IMAGE=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
+          IMAGE_ID=$(jq -n \
+            --arg img "$IMAGE" \
+            '{"ImageId": $img}')
+          aws ec2 create-launch-template-version \
+            --launch-template-name "$LAUNCH_CONFIG" \
+            --version-description updateAMI --source-version 1 \
+            --launch-template-data="$IMAGE_ID"
+          TEMPLATE_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-name="$LAUNCH_CONFIG" \
+            --filters="Name=is-default-version,Values=false" \
+            --query 'sort_by(LaunchTemplateVersions, &CreateTime)[-1].[VersionNumber]' --output text)
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME \
+            --launch-template LaunchTemplateName="$LAUNCH_CONFIG",Version=$TEMPLATE_VERSION
+          aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name $ASG_NAME --strategy Rolling
+          printf "Instance refresh in progress"
+          while true;
+          do
+            instance_refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME \
+              --query "InstanceRefreshes[0].Status" --output text)
+            if [ "$instance_refresh_status" = "Successful" ]; then
+              printf "\nInstance refresh successful!"
+              break
+            fi
+            if [ "$instance_refresh_status" = "Cancelling" ] || [ "$instance_refresh_status" = "Cancelled" ] || [ "$instance_refresh_status" = "Failed" ]; then
+              printf "\nInstance refresh failed!"
+              exit 1
+            fi
+            echo -ne "."
+            sleep 10
+          done
 
-  # on:
-  #   push:
-  #     branches:
-  #       - main    #branch name change
-
-  # jobs:
-  #   build-ami:
-  #     runs-on: ubuntu-latest
-  #     #   postgres:
-  #     #     image: postgres:latest
-  #     #     env:
-  #     #       POSTGRES_DB: ${{ secrets.DB_DATABASE }}
-  #     #       POSTGRES_USER: ${{ secrets.DB_USER }}
-  #     #       POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
-  #     #       POSTGRES_PORT: ${{ secrets.DB_PORT }}
-  #     #       POSTGRES_HOST: ${{ secrets.DB_HOST }}
-  #     #     ports:
-  #     #       - 5432:5432
-  #     #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
-
-
-  #     # steps:
-  #     #   - name: Checkout Code
-  #     #     uses: actions/checkout@v2
-
-  #     #   - name: "Create env file"
-  #     #     run: |
-  #     #       touch .env
-  #     #       echo PGDATABASE=${{ secrets.DB_DATABASE }} >> .env
-  #     #       echo PGUSER=${{ secrets.DB_USER }} >> .env
-  #     #       echo PGPASSWORD=${{ secrets.DB_PASSWORD }} >> .env
-  #     #       echo PGPORT=${{ secrets.DB_PORT }} >> .env
-  #     #       echo PGHOST=${{ secrets.DB_HOST }} >> .env
-  #     #       echo "cat .env"
-  #     #       cat .env
-  #     #       echo "ls -a ."
-  #     #       ls -a .
-  #     #       echo "ls -a ${{ github.workspace }}"
-  #     #       ls -a ${{ github.workspace }}
-
-  
-
-  #     #   - name: Set up Node.js
-  #     #     uses: actions/setup-node@v2
-  #     #     with:
-  #     #       node-version: 18.x
-
-  
-
-  #     #   - name: Install Dependencies
-  #     #     run: npm install
-
-  
-
-  #     #   - name: Run Integration Tests
-  #     #     run: npm run test
-
-  #       - name: Checkout Repository
-  #         uses: actions/checkout@v2
-
-          
-  #       - name: Create zip archive from current directory
-  #         run: |
-  #           mkdir artifacts
-  #           zip -r artifacts/webapp.zip . -x "*.git*"
-
-  #       - name: Install Packer
-  #         run: |
-  #           PACKER_VERSION="1.9.4"  
-  #           wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
-  #           unzip packer_${PACKER_VERSION}_linux_amd64.zip
-  #           sudo mv packer /usr/local/bin/
-  #           packer --version
-
-
-  #       - name: Initialize Packer
-  #         run: packer init main.pkr.hcl
-
-  #       - name: Build Custom AMI
-  #         env:
-  #           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         run: packer build main.pkr.hcl
+      # asg_launch_config
